### PR TITLE
Implementation of allowed paths configuration option

### PR DESCRIPTION
**Pull request by sapajune**
Implements limiting on the collector-sidecar side what logs can be configured to be collected via new allowed_paths configuration option. The option is only applicable to filebeat collectors.

When log collection configuration is updated from server the log path glob expressions are matched against set of allowed paths regular expressions. All the paths for prospector must match at least one allowed path expression or prospector is discarded with logged warning message. For backwards compatibility, anything can be collected if no allowed_paths are configured.

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanks for the PR!
I have the feeling this problem should be solved in the server rather than the Sidecar itself?
Our current approach was to keep the configuration file clean of collector specific options. It basically just defines the connection to the Graylog server.

On the other hand solving this problem on the Sidecar side doesn't allow to provide feedback to the user. When you set an invalid combination of allowed-paths and pathes to collect the user would expect some kind or error message in the web interface. But now the prospector is silently removed.

**Comment by sapajune** [comment]
Thanks for the quick review!

I agree on the fact that it is not obvious to user on the server side since it's only seen as logs not getting collected. I haven't noticed capability of reporting such verification errors to server. Similar cases that are not immediately visible in the web interface exist elsewhere (usually triggered by misconfiguration).

Solving this otherwise on the server boils down to two options:
- Using file permissions which can be cumbersome to setup
- Not use collector-sidecar and configure just filebeat which disallows any configuration from Graylog server

In our own case we run Graylog as part of SAAS offering and cannot control file permissions on customer's server. Also using bare filebeat is more difficult to configure since the access to servers is limited.

I can appreciate the clean approach for sidecar configuration and see it might be obstacle for approving this PR.

**Comment by mariussturm** [comment]
I would put this feature request on hold for now. We will move most of the configuration logic from the Sidecar into server in the next month. I would say you use your costume build for now. Once we restructured the parts we can take another look. It should be much easier then to solve your problem in a proper way.

Anyway, thanks a lot for the feedback!

**Comment by sapajune** [comment]
Ok. We'll go with our custom build now.

**Pull request closed without merging**
