### PR TITLE
Add upgrade support and improve windows installer

### LINKED ISSUE #365: Check Sidecar upgrade on windows
It seems the sidecar upgrade on Windows is not well tested and defined.
According to https://community.graylog.org/t/sidecar-upgrades-and-default-configs/10158
the uninstaller also deletes the `node-id` file.

This prevents us from recommending to simply uninstall and reinstall the sidecar to
perform an upgrade.

Copying over the running binary is not an option on Windows, as their poor FS implementation
lacks the concept of reference counted inodes :man_facepalming: 

We need to come up with a properly tested upgrade path solution.

### LINKED ISSUE #432: Upgrading sidecar from 1.1 to 1.2
I have a fleet of Windows Sidecar v1.1 and I want to upgrade them to 1.2. 
What would be the simplest recommended way to do so ? Do I have to I uninstall v1.1 first ?

### PR DESCRIPTION
**Pull request by mpfz0r**
The installer can now also upgrade existing sidcar installations.
    It detects this by the presence of an existing sidecar.yml config.
    In upgrade mode it skip the configuration page.

Additionally the installer will now also register the sidecar
    service automatically. Making this extra command line step obsolete.
    
For debugging purposes, we write a installerlog.txt file now.
    
Improve welcome message test to also show the version and mention the
    autmatic upgrade mode.
    
Only replace the winlogbeat and filebeat collector binaries AFTER
    we stopped the sidecar. Otherwise the files might still be locked
    and the upgrade fails.

Suppport `-NODEID param` for silent installer
Also fix default node-id file location for 32-bit installs

Fixes #365 
Fixes #432

### CODE REVIEW

**Review by thll — CHANGES_REQUESTED** [review]
Looks good in general and appears to work. Any idea why logging to the console under PowerShell looks off?

Would be nice if we could fix that.

Here's what happens when I install and then hit `<Enter>` a couple of times:

https://user-images.githubusercontent.com/886541/193780295-50629764-a901-46a7-9c83-c5de3e90c677.mp4

**Comment by mpfz0r** [comment]
> Would be nice if we could fix that.

@thll I agree, but I was running out of time and wasn't sure if it's worth the effort.

**Comment by boosty** [comment]
@mpfz0r Depends on how hard is it fix. A few hours during this cool-down seem ok to me.

**Review by thll — APPROVED** [review]
Fixing that console logging behaviour is not a must, so I'm approving the PR.

**Pull request merged**
